name: Reuse other workflow 2

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable2.yml
    with:
      who-to-greet: '@MelinaCir'
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "The time was ${{ needs.call-workflow.outputs.current-time }}"
